//export 'main_page.dart';
//export 'main_left_page.dart';
export 'splash_page.dart';
export 'search_page.dart';
export 'collection_page.dart';
export 'setting_page.dart';
export 'about_page.dart';
export 'share_page.dart';
export 'home_page.dart';